# Generated by Django 4.1.7 on 2023-04-07 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('Empno', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=200)),
                ('Job', models.CharField(max_length=200)),
                ('Mgr', models.IntegerField()),
                ('Hiredate', models.DateField()),
                ('Sal', models.IntegerField()),
                ('Comm', models.IntegerField()),
                ('Dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
