# Generated by Django 4.1.7 on 2023-04-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='Comm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='Hiredate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='Mgr',
            field=models.IntegerField(null=True),
        ),
    ]
